-- MySQL Script generated by MySQL Workbench
-- Sat Mar 28 04:01:50 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema puzzleDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema puzzleDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `puzzleDB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `puzzleDB` ;

-- -----------------------------------------------------
-- Table `puzzleDB`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puzzleDB`.`Users` (
  `userID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `admins` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `pseudo` (`pseudo` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `puzzleDB`.`Partie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puzzleDB`.`Partie` (
  `gameID` INT NOT NULL AUTO_INCREMENT,
  `userID` INT UNSIGNED NOT NULL,
  `score` INT NOT NULL,
  `difficulte` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`gameID`),
  INDEX `userID` (`userID` ASC) VISIBLE,
  CONSTRAINT `Partie_ibfk_1`
    FOREIGN KEY (`userID`)
    REFERENCES `puzzleDB`.`Users` (`userID`))
ENGINE = InnoDB
AUTO_INCREMENT = 246
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `puzzleDB`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puzzleDB`.`Post` (
  `postID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userID` INT UNSIGNED NOT NULL,
  `image` VARCHAR(300) NOT NULL,
  `reactCount` INT UNSIGNED NULL DEFAULT '0',
  PRIMARY KEY (`postID`),
  INDEX `userID` (`userID` ASC) VISIBLE,
  CONSTRAINT `Post_ibfk_1`
    FOREIGN KEY (`userID`)
    REFERENCES `puzzleDB`.`Users` (`userID`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `puzzleDB`.`Reaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puzzleDB`.`Reaction` (
  `reactID` INT NOT NULL AUTO_INCREMENT,
  `userID` INT UNSIGNED NULL DEFAULT NULL,
  `postID` INT UNSIGNED NULL DEFAULT NULL,
  `react` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`reactID`),
  INDEX `userID` (`userID` ASC) VISIBLE,
  INDEX `fk_Reaction` (`postID` ASC) VISIBLE,
  CONSTRAINT `fk_Reaction`
    FOREIGN KEY (`postID`)
    REFERENCES `puzzleDB`.`Post` (`postID`)
    ON DELETE CASCADE,
  CONSTRAINT `Reaction_ibfk_1`
    FOREIGN KEY (`userID`)
    REFERENCES `puzzleDB`.`Users` (`userID`))
ENGINE = InnoDB
AUTO_INCREMENT = 72
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
